[project]
name = "monitoring-automation"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "playwright>=1.58.0",
    "python-dotenv>=1.2.1",
]
